name: markdown_builder
version: 1.0.0
description: Dart build plugin for transforming Markdown documents to HTML.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/markdown_builder
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  build: ">=0.12.0 <2.0.0"
  build_config: ">=0.3.0 <2.0.0"
  markdown: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.0.0
